---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01ezbxtt3hhj8bnnh0vzascxd4"
    - from: "jfevt@*"
      to: "jfevt@01ezbxta5r43dk06bp4xz708ps"
    - from: "jfrt@*"
      to: "jfrt@01ezbxvv4h7r170891d32s1zds"
    - from: "jffe@*"
      to: "jffe@000"
    - from: "jfmd@*"
      to: "jfmd@01ezbxtvzmhwsnfvqhk7cz3vve"
licenses:
- server-name: "7df5221f0f5d"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlOMVF3Tmpvek16bzFNQzR4TnpoYUNtbGtPaUJsTkRsak9XVmlNaTFoWVdKaUxUUXlZamt0\r\
    \nWWpJeU5TMDRORGs1WkRaa05UVXdaRGdLYjNkdVpYSTZJR1JrWkFwd2NtOXdaWEowYVdWek9pQjdm\r\
    \nUXB6YVdkdVlYUjFjbVU2SUc1MWJHd0tkSEpwWVd3NklIUnlkV1VLZEhsd1pUb2dWRkpKUVV3S2Rt\r\
    \nRnNhV1JHY205dE9pQXlNREl4TFRBeUxUSTFWREEyT2pNek9qVXdMakUzT0ZvSwogICAgc2lnbmF0\r\
    \ndXJlOiBBRjUzU3JveTNtU0JhUnV2QmRNQUZkYzU5MDl2U1FWdGd0ejdhSStWSVVQa1ptKzFPSzFy\r\
    \nU1lnRGNZTnEyMU5ZZGJ5dVE5RmpCanVlM0RFREpEWmhQcUZHWDBKbkJMb2lGQ0d3QXA0RmtOdVB4\r\
    \na05CU2tKQmFiRXJnaUVqUmZ6VzY4V2VTNDFqbU9VTVdRY3hIdzZSQ1VBRUhjTU53Y1dONmtVVmN6\r\
    \nYWJId0JsWWpJSUlqQVptRSsxcUtRM0ZpNGdrTzFGdHBoLzZ4NW5YaDZ4TlVlNzdjTW50RFJlNVNk\r\
    \nRXdMVXhrZCtBZHpXZHhXQ2Zkd0hZTGhGM1dkR0VpS0t5eXgxL3RJMlpObjVqdm5OVk5UZlNVSkVN\r\
    \nTEpRM2N2UlJtMXJoQWFVK0dScGZaTDY2ZVlxL09VWVZZNkh1RXJ4WlJJSEt4ajg5aVBLbzc0eFF5\r\
    \nNXZmWlE9PQp2ZXJzaW9uOiAxCg==\r\n"
- server-name: "1d06c85b6f22"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlOMVF3Tmpvek16bzFNQzR4TnpoYUNtbGtPaUJsTkRsak9XVmlNaTFoWVdKaUxUUXlZamt0\r\
    \nWWpJeU5TMDRORGs1WkRaa05UVXdaRGdLYjNkdVpYSTZJR1JrWkFwd2NtOXdaWEowYVdWek9pQjdm\r\
    \nUXB6YVdkdVlYUjFjbVU2SUc1MWJHd0tkSEpwWVd3NklIUnlkV1VLZEhsd1pUb2dWRkpKUVV3S2Rt\r\
    \nRnNhV1JHY205dE9pQXlNREl4TFRBeUxUSTFWREEyT2pNek9qVXdMakUzT0ZvSwogICAgc2lnbmF0\r\
    \ndXJlOiBBRjUzU3JveTNtU0JhUnV2QmRNQUZkYzU5MDl2U1FWdGd0ejdhSStWSVVQa1ptKzFPSzFy\r\
    \nU1lnRGNZTnEyMU5ZZGJ5dVE5RmpCanVlM0RFREpEWmhQcUZHWDBKbkJMb2lGQ0d3QXA0RmtOdVB4\r\
    \na05CU2tKQmFiRXJnaUVqUmZ6VzY4V2VTNDFqbU9VTVdRY3hIdzZSQ1VBRUhjTU53Y1dONmtVVmN6\r\
    \nYWJId0JsWWpJSUlqQVptRSsxcUtRM0ZpNGdrTzFGdHBoLzZ4NW5YaDZ4TlVlNzdjTW50RFJlNVNk\r\
    \nRXdMVXhrZCtBZHpXZHhXQ2Zkd0hZTGhGM1dkR0VpS0t5eXgxL3RJMlpObjVqdm5OVk5UZlNVSkVN\r\
    \nTEpRM2N2UlJtMXJoQWFVK0dScGZaTDY2ZVlxL09VWVZZNkh1RXJ4WlJJSEt4ajg5aVBLbzc0eFF5\r\
    \nNXZmWlE9PQp2ZXJzaW9uOiAxCg==\r\n"
- server-name: "9f3337896b83"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlOMVF3Tmpvek16bzFNQzR4TnpoYUNtbGtPaUJsTkRsak9XVmlNaTFoWVdKaUxUUXlZamt0\r\
    \nWWpJeU5TMDRORGs1WkRaa05UVXdaRGdLYjNkdVpYSTZJR1JrWkFwd2NtOXdaWEowYVdWek9pQjdm\r\
    \nUXB6YVdkdVlYUjFjbVU2SUc1MWJHd0tkSEpwWVd3NklIUnlkV1VLZEhsd1pUb2dWRkpKUVV3S2Rt\r\
    \nRnNhV1JHY205dE9pQXlNREl4TFRBeUxUSTFWREEyT2pNek9qVXdMakUzT0ZvSwogICAgc2lnbmF0\r\
    \ndXJlOiBBRjUzU3JveTNtU0JhUnV2QmRNQUZkYzU5MDl2U1FWdGd0ejdhSStWSVVQa1ptKzFPSzFy\r\
    \nU1lnRGNZTnEyMU5ZZGJ5dVE5RmpCanVlM0RFREpEWmhQcUZHWDBKbkJMb2lGQ0d3QXA0RmtOdVB4\r\
    \na05CU2tKQmFiRXJnaUVqUmZ6VzY4V2VTNDFqbU9VTVdRY3hIdzZSQ1VBRUhjTU53Y1dONmtVVmN6\r\
    \nYWJId0JsWWpJSUlqQVptRSsxcUtRM0ZpNGdrTzFGdHBoLzZ4NW5YaDZ4TlVlNzdjTW50RFJlNVNk\r\
    \nRXdMVXhrZCtBZHpXZHhXQ2Zkd0hZTGhGM1dkR0VpS0t5eXgxL3RJMlpObjVqdm5OVk5UZlNVSkVN\r\
    \nTEpRM2N2UlJtMXJoQWFVK0dScGZaTDY2ZVlxL09VWVZZNkh1RXJ4WlJJSEt4ajg5aVBLbzc0eFF5\r\
    \nNXZmWlE9PQp2ZXJzaW9uOiAxCg==\r\n"
schema-version: 2
